### ISSUE TITLE
Do not validate that test folder exists

### ISSUE THREAD

**Issue by dbashford** [dbazile/mimosa-phantomcss#4]
You currently [validate that the testDirectory exists](https://github.com/dbazile/mimosa-phantomcss/blob/master/src/config.js#L38) but that causes issues if you want to use something in the public directory (like files that have been defeatured) for tests since the public directory can be missing.

Might be best to move the check for folder existing to right before the tests execute.

**Comment by dbazile** [comment]
Closed by https://github.com/dbazile/mimosa-phantomcss/commit/9d462e09ee17bf9722e465e730c00587f045664c
